services:
  - type: web
    name: llm-quiz-api
    env: python
    pythonVersion: 3.13.4   # keep 3.13 if you upgrade pandas
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
